ExamenMvcLibrosMauricio/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcLibrosMauricio.Models
{
    [Table("USUARIOS")]
    public class Usuario
    {
        [Key]
        [Column("IdUsuario")]
        public int IdUsuario { get; set; }
        [Column("Nombre")]
        public string Nombre { get; set; }
        [Column("Apellidos")]
        public string Apellidos { get; set; }
        [Column("Email")]
        public string Email { get; set; }
        [Column("Pass")]
        public string Pass { get; set; }
        [Column("Foto")]
        public string Foto { get; set; }
    }
}

ExamenMvcLibrosMauricio/Controllers/LibroController.cs
using ExamenMvcLibrosMauricio.Filters;
using ExamenMvcLibrosMauricio.Models;
using ExamenMvcLibrosMauricio.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using ExamenMvcLibrosMauricio.Extensions;
using System.Security.Claims;

namespace ExamenMvcLibrosMauricio.Controllers
{
    public class LibroController : Controller
    {
        private RepositoryLibros repo;
        private IMemoryCache memoryCache;

        public LibroController(RepositoryLibros repo, IMemoryCache memoryCache)
        {
            this.repo = repo;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Home()
        {
            List<Libro> libros = await this.repo.GetAllLibrosAsync();
            return View(libros);
        }

        public async Task<IActionResult> Genero(int idgenero)
        {
            List<Libro> libros = await this.repo.GetAllLibrosByGeneroAsync(idgenero);
            return View(libros);
        }

        public async Task<IActionResult> Detalles(int idlibro)
        {
            Libro libro = await this.repo.GetLibroByIdLibroAsync(idlibro);
            return View(libro);
        }

        public async Task<IActionResult> Comprar(int idlibro)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito == null)
            {
                carrito = new List<int>();
            }
            if (carrito.Any(id => id == idlibro) == false)
            {
                carrito.Add(idlibro);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }

            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> Quitar(int idlibro)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito != null)
            {
                if (carrito.Any(id => id == idlibro) == true)
                {
                    int id = carrito.Find(id => id == idlibro);
                    carrito.Remove(id);
                    if (carrito.Count == 0)
                    {
                        HttpContext.Session.Remove("CARRITO");
                    }
                    else
                    {
                        HttpContext.Session.SetObject("CARRITO", carrito);
                    }
                }
            }
            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> Carrito()
        {
            List<int> idslibro = HttpContext.Session.GetObject<List<int>>("CARRITO");
            List<Libro> libros = null;
            if (idslibro != null)
            {
                libros = await this.repo.GetAllLibrosByListIdsAsync(idslibro);
            }
            return View(libros);
        }
        [AuthorizeUsuarios]
        public async Task<IActionResult> UsuarioPerfil()
        {
            return View();
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> FinalizarCompra()
        {
            List<int> idslibro = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (idslibro != null)
            {
                int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                await this.repo.InsertPedidoAsync(idslibro, idusuario);
                HttpContext.Session.Remove("CARRITO");
            }
            return RedirectToAction("Pedidos");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Pedidos()
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            List<PedidoView> pedidoViews = await this.repo.GetAllPedidoViewByIdUsuarioAsync(idusuario);
            return View(pedidoViews);
        }
    }
}

ExamenMvcLibrosMauricio/Controllers/ManagedController.cs
using ExamenMvcLibrosMauricio.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ExamenMvcLibrosMauricio.Repositories;

namespace ExamenMvcLibrosMauricio.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryLibros repo;

        public ManagedController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            Usuario usuario = await this.repo.LogInUserAsync(email, password);
            if (usuario != null)
            {
                ClaimsIdentity identity = new ClaimsIdentity(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    ClaimTypes.Name,
                    ClaimTypes.Role);
                List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario+""),
                    new Claim(ClaimTypes.Name, usuario.Nombre),
                    new Claim(ClaimTypes.Surname, usuario.Apellidos),
                    new Claim(ClaimTypes.Email, usuario.Email),
                    new Claim(ClaimTypes.UserData, usuario.Foto)
                };
                identity.AddClaims(claims);
                ClaimsPrincipal usePrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    usePrincipal);
                string controller = TempData["controller"].ToString();
                string action = TempData["action"].ToString();
                return RedirectToAction(action, controller);
            }
            else
            {
                ViewData["ERROR"] = "Credenciales incorrectas";
                return View();
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Home", "Libro");
        }
    }
}

ExamenMvcLibrosMauricio/ViewComponents/MenuGenerosViewComponent.cs
using ExamenMvcLibrosMauricio.Models;
using ExamenMvcLibrosMauricio.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExamenMvcLibrosMauricio.ViewComponents
{
    [ViewComponent(Name = "MenuGeneros")]
    public class MenuGenerosViewComponent:ViewComponent
    {
        private RepositoryLibros repo;

        public MenuGenerosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetAllGenerosAsync();
            return View(generos);
        }
    }
}

ExamenMvcLibrosMauricio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenMvcLibrosMauricio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenMvcLibrosMauricio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Libro" asp-action="Home">ExamenMvcLibrosMauricio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Home">Home</a>
                        </li>
                        @await Component.InvokeAsync("MenuGeneros")
                        <partial name="_LibrosCarrito" />
                        <partial name="_Usuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExamenMvcLibrosMauricio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExamenMvcLibrosMauricio/Views/Shared/_LibrosCarrito.cshtml
@{
    List<int> ids = Context.Session.GetObject<List<int>>("CARRITO");
}
@if(ids!=null){

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Carrito">Libros carrito:@ids.Count</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Carrito">Carrito: 0</a>
    </li>
}

ExamenMvcLibrosMauricio/Views/Shared/_Usuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    <li>
        <a class="nav-link text-dark" asp-controller="Libro" asp-action="UsuarioPerfil">Login</a>
    </li>
}
else
{
    <li>
        <a class="nav-link text-dark" asp-controller="Libro" asp-action="UsuarioPerfil">Perfil</a>
    </li>
    <li>
        <a class="nav-link text-dark" asp-controller="Libro" asp-action="Pedidos">Pedidos</a>
    </li>
    <li>
        <a class="nav-link text-danger" asp-controller="Managed" asp-action="Logout">Cerrar sesión</a>
    </li>
}