ExamenMvcLibrosMauricio/Models/Genero.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcLibrosMauricio.Models
{
    [Table("GENEROS")]
    public class Genero
    {
        [Key]
        [Column("IdGenero")]
        public int IdGenero { get; set; }
        [Column("Nombre")]
        public string Nombre { get; set; }
    }
}

ExamenMvcLibrosMauricio/Models/Libro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcLibrosMauricio.Models
{
    [Table("LIBROS")]
    public class Libro
    {
        [Key]
        [Column("IdLibro")]
        public int IdLibro { get; set; }
        [Column("Titulo")]
        public string Titulo { get; set; }
        [Column("Autor")]
        public string Autor { get; set; }
        [Column("Editorial")]
        public string Editorial { get; set; }
        [Column("Portada")]
        public string Portada { get; set; }
        [Column("Resumen")]
        public string Resumen { get; set; }
        [Column("Precio")]
        public int Precio { get; set; }
        [Column("IdGenero")]
        public int IdGenero { get; set; }

    }
}

ExamenMvcLibrosMauricio/Models/Pedido.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcLibrosMauricio.Models
{
    [Table("PEDIDOS")]
    public class Pedido
    {
        [Key]
        [Column("IDPEDIDO")]
        public int IdPedido { get; set; }
        [Column("IDFACTURA")]
        public int IdFactura { get; set; }
        [Column("FECHA")]
        public DateTime Fecha { get; set; }
        [Column("IDLIBRO")]
        public int IdLibro { get; set; }
        [Column("IDUSUARIO")]
        public int IdUsuario { get; set; }
        [Column("CANTIDAD")]
        public int Cantidad { get; set; }
    }
}

ExamenMvcLibrosMauricio/Models/PedidoView.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcLibrosMauricio.Models
{
    [Table("VISTAPEDIDOS")]
    public class PedidoView
    {
        [Key]
        [Column("IDVISTAPEDIDOS")]
        public int IdPedidoView { get; set; }
        [Column("IdUsuario")]
        public int IdUsuario { get; set; }
        [Column("Nombre")]
        public string Nombre { get; set; }
        [Column("Apellidos")]
        public string Apellidos { get; set; }
        [Column("Titulo")]
        public string Titulo { get; set; }
        [Column("Precio")]
        public int Precio { get; set; }
        [Column("Portada")]
        public string Portada { get; set; }
        [Column("FECHA")]
        public DateTime Fecha { get; set; }
        [Column("PRECIOFINAL")]
        public int PrecioFinal { get; set; }
    }
}

ExamenMvcLibrosMauricio/Controllers/HomeController.cs
using ExamenMvcLibrosMauricio.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamenMvcLibrosMauricio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenMvcLibrosMauricio/Controllers/LibroController.cs
using ExamenMvcLibrosMauricio.Filters;
using ExamenMvcLibrosMauricio.Models;
using ExamenMvcLibrosMauricio.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using ExamenMvcLibrosMauricio.Extensions;
using System.Security.Claims;

namespace ExamenMvcLibrosMauricio.Controllers
{
    public class LibroController : Controller
    {
        private RepositoryLibros repo;
        private IMemoryCache memoryCache;

        public LibroController(RepositoryLibros repo, IMemoryCache memoryCache)
        {
            this.repo = repo;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Home()
        {
            List<Libro> libros = await this.repo.GetAllLibrosAsync();
            return View(libros);
        }

        public async Task<IActionResult> Genero(int idgenero)
        {
            List<Libro> libros = await this.repo.GetAllLibrosByGeneroAsync(idgenero);
            return View(libros);
        }

        public async Task<IActionResult> Detalles(int idlibro)
        {
            Libro libro = await this.repo.GetLibroByIdLibroAsync(idlibro);
            return View(libro);
        }

        public async Task<IActionResult> Comprar(int idlibro)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito == null)
            {
                carrito = new List<int>();
            }
            if (carrito.Any(id => id == idlibro) == false)
            {
                carrito.Add(idlibro);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }

            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> Quitar(int idlibro)
        {
            List<int> carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (carrito != null)
            {
                if (carrito.Any(id => id == idlibro) == true)
                {
                    int id = carrito.Find(id => id == idlibro);
                    carrito.Remove(id);
                    if (carrito.Count == 0)
                    {
                        HttpContext.Session.Remove("CARRITO");
                    }
                    else
                    {
                        HttpContext.Session.SetObject("CARRITO", carrito);
                    }
                }
            }
            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> Carrito()
        {
            List<int> idslibro = HttpContext.Session.GetObject<List<int>>("CARRITO");
            List<Libro> libros = null;
            if (idslibro != null)
            {
                libros = await this.repo.GetAllLibrosByListIdsAsync(idslibro);
            }
            return View(libros);
        }
        [AuthorizeUsuarios]
        public async Task<IActionResult> UsuarioPerfil()
        {
            return View();
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> FinalizarCompra()
        {
            List<int> idslibro = HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (idslibro != null)
            {
                int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                await this.repo.InsertPedidoAsync(idslibro, idusuario);
                HttpContext.Session.Remove("CARRITO");
            }
            return RedirectToAction("Pedidos");
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> Pedidos()
        {
            int idusuario = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            List<PedidoView> pedidoViews = await this.repo.GetAllPedidoViewByIdUsuarioAsync(idusuario);
            return View(pedidoViews);
        }
    }
}

ExamenMvcLibrosMauricio/Views/Libro/Carrito.cshtml
@model List<Libro>

<table class="table">
    <thead>
        <tr>
            <th>
                Libro
            </th>
            <th>
                Portada
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Titulo
                    </td>
                    <td>
                        <img src="~/images/@item.Portada" class="rounded" style="width:10rem;height:15rem;" />
                    </td>
                    <td>
                        <a asp-controller="Libro" asp-action="Detalles" asp-route-idlibro="@item.IdLibro" class="btn btn-primary">Detalles</a>
                    </td>
                    <td>
                        <a asp-controller="Libro" asp-action="Quitar" asp-route-idlibro="@item.IdLibro" class="btn btn-danger">Quitar</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4">Sin libros</td>
            </tr>
        }
    </tbody>
</table>
@if (Model != null)
{

    <a asp-controller="Libro" asp-action="FinalizarCompra" class="btn btn-primary">Finalizar compra</a>
}

ExamenMvcLibrosMauricio/Views/Libro/Detalles.cshtml
@model Libro

<h1>Detalles</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Titulo
        </dt>
        <dd class = "col-sm-10">
            @Model.Titulo
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Model.Autor
        </dd>
        <dt class = "col-sm-2">
            Editorial
        </dt>
        <dd class = "col-sm-10">
            @Model.Editorial
        </dd>
        <dt class = "col-sm-2">
            Portada
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@Model.Portada" class="rounded" style="width:10rem;height:15rem;" />
        </dd>
        <dt class = "col-sm-2">
            Resumen
        </dt>
        <dd class = "col-sm-10">
            @Model.Resumen
        </dd>
        <dt class = "col-sm-2">
            Precio
        </dt>
        <dd class = "col-sm-10">
            @Model.Precio€
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Libro" asp-action="Comprar" asp-route-idlibro="@Model.IdLibro" class="btn btn-primary">Comprar</a>
</div>

ExamenMvcLibrosMauricio/Views/Libro/Genero.cshtml
@model List<Libro>
<h1 class="text-primary">Libros genero</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Libro
            </th>
            <th>
                Portada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Titulo
                </td>
                <td>
                    <img src="~/images/@item.Portada" class="rounded" style="width:10rem;height:15rem;" />
                </td>
                <td>
                    <a asp-controller="Libro" asp-action="Detalles" asp-route-idlibro="@item.IdLibro" class="btn btn-primary">Detalles</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ExamenMvcLibrosMauricio/Views/Libro/Home.cshtml
@model List<Libro>
<h1 class="text-primary">Home</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Libro
            </th>
            <th>
                Portada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @item.Titulo
            </td>
            <td>
                    <img src="~/images/@item.Portada" class="rounded" style="width:10rem;height:15rem;" />
            </td>
            <td>
                <a asp-controller="Libro" asp-action="Detalles" asp-route-idlibro="@item.IdLibro" class="btn btn-primary">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExamenMvcLibrosMauricio/Views/Libro/Pedidos.cshtml
@model List<PedidoView>

<h1 class="text-primary">Pedidos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Apellidos
            </th>
            <th>
                Titulo
            </th>
            <th>
                Precio
            </th>
            <th>
                Portada
            </th>
            <th>
                Fecha Pedido
            </th>
            <th>
                Total pedido
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count != 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Nombre
                    </td>
                    <td>
                        @item.Apellidos
                    </td>
                    <td>
                        @item.Titulo
                    </td>
                    <td>
                        @item.Precio
                    </td>
                    <td>
                        <img src="~/images/@item.Portada" class="rounded" style="width:10rem;height:15rem;" />
                    </td>
                    <td>
                        @item.Fecha
                    </td>
                    <td>
                        @item.PrecioFinal
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7">Sin pedidos</td>
            </tr>
        }
    </tbody>
</table>

ExamenMvcLibrosMauricio/Views/Libro/UsuarioPerfil.cshtml
@model ExamenMvcLibrosMauricio.Models.Usuario

@{
    string nombre = Context.User.FindFirst(ClaimTypes.Name).Value;
    string apellidos = Context.User.FindFirst(ClaimTypes.Surname).Value;
    string email = Context.User.FindFirst(ClaimTypes.Email).Value;
    string foto = Context.User.FindFirst(ClaimTypes.UserData).Value;
}

<h1>UsuarioPerfil</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Nombre
        </dt>
        <dd class = "col-sm-10">
            @nombre
        </dd>
        <dt class = "col-sm-2">
           Apellidos
        </dt>
        <dd class = "col-sm-10">
            @apellidos
        </dd>
        <dt class = "col-sm-2">
           Email
        </dt>
        <dd class = "col-sm-10">
            @email
        </dd>
        <dt class = "col-sm-2">
           Foto
        </dt>
        <dd class = "col-sm-10">
            <img src="~/images/@foto" class="rounded" style="width:10rem;height:15rem;" />
            
        </dd>
    </dl>
</div>